# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TopDrawer' do

pod 'JSQMessagesViewController'
pod 'Material'
end

target 'TopDrawerTests' do

end

target 'TopDrawerUITests' do

end

target 'TopDrawerActionExtension' do

end

